backend:
  name: github
  branch: master
  repo: munich-center/documentation
  api_root: https://api.github.ibm.com
  base_url: https://netlify-ibm-auth.kgir4j0apvr.eu-de.codeengine.appdomain.cloud
  auth_endpoint: auth

publish_mode: editorial_workflow
media_folder: static/media
public_folder: /media
site_url: https://pages.github.ibm.com/munich-center/portfolio-website-publish/
collections:
  - name: demos
    label: Demos
    label_singular: 'Demo'
    folder: content/demos
    path: '{{title}}/index'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: Template
        name: template
        widget: hidden
        default: post
      - label: Title
        name: title
        widget: string
      - label: Author
        name: author
        widget: select
        options: ["Francis Powlesland", "Martin Junghans"]
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
        required: false
      - label: Publish Date
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: text
      - label: Category
        name: category
        widget: string
      - label: Prerequisites
        name: prerequisites
        hint: "Content: contains a list of all physical devices needed for the demo. Format: list of devices preferred"
        widget: markdown
      - label: Cold Start
        name: cold-start
        widget: markdown
        hint: "Content: step by step guide for the complete setup process, screenshots are highly recommended; must enable any lab member to setup the demo. Starting point: all devices are turned off. End point: the demo is ready to be presented. Format: (nested) list of steps preferred"
      - label: Body
        name: body
        widget: hidden
      - label: Tags
        name: tags
        widget: list
  - name: pages
    label: Pages
    label_singular: 'Page'
    folder: content/pages
    create: true
    slug: '{{slug}}'
    fields:
      - label: Template
        name: template
        widget: hidden
        default: page
      - label: Title
        name: title
        widget: string
      - label: Draft
        name: draft
        widget: boolean
        default: true
      - label: Body
        name: body
        widget: markdown
